<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Zásady ochrany osobných údajov</title>
</head>
<body>
<p><span style="font-weight: 400;">Z&aacute;sady ochrany osobn&yacute;ch &uacute;dajov (ďalej ZOOU).</span></p>
<p><span style="font-weight: 400;">Tento dokument stanovuje ako použ&iacute;vame, spracov&aacute;vame a&nbsp;chr&aacute;nime Va&scaron;e osobn&eacute; &uacute;daje, ktor&eacute; ste n&aacute;m spr&iacute;stupnili pri n&aacute;v&scaron;teve tejto webovej str&aacute;nky,&nbsp;pri využ&iacute;van&iacute; produktov/služieb </span><span style="font-weight: 400;">s</span><span style="font-weight: 400;">poločnosti </span><span style="font-weight: 400;">ABC Mobile O&Uuml; a&nbsp;pri využ&iacute;van&iacute; ďal&scaron;ieho obsahu.&nbsp; Kon&aacute;me vždy v&nbsp;z&aacute;ujme n&aacute;&scaron;ho z&aacute;kazn&iacute;ka a&nbsp;spr&iacute;stupňujeme inform&aacute;cie o&nbsp;tom, ako spracov&aacute;vame Va&scaron;e osobn&eacute; &uacute;daje.</span></p>
<p><span style="font-weight: 400;">Znamen&aacute; to, že sme odhodlan&iacute; chr&aacute;niť a&nbsp;zabezpečiť Va&scaron;e osobn&eacute; d&aacute;ta, ktor&eacute; ste n&aacute;m zverili. Z&aacute;roveň V&aacute;s informujeme o&nbsp;tom, ako n&aacute;s m&ocirc;žete kontaktovať v&nbsp;pr&iacute;pade, že m&aacute;te ot&aacute;zky ohľadne Va&scaron;ich osobn&yacute;ch d&aacute;t. Tieto ZOOU sa t&yacute;kaj&uacute; ak&yacute;chkoľvek inform&aacute;ci&iacute;, ktor&eacute; sme z&iacute;skali prostredn&iacute;ctvom na&scaron;ej vlastnej webovej str&aacute;nky/aplik&aacute;cie, a&nbsp;taktiež prostredn&iacute;ctvom soci&aacute;lnych siet&iacute; a&nbsp;webov&yacute;ch str&aacute;nok na&scaron;ich partnerov.</span></p>
<p><span style="font-weight: 400;">ZOOU m&ocirc;žu byť z&nbsp;času na čas upravovan&eacute;. Pokiaľ V&aacute;m z&aacute;lež&iacute; na Va&scaron;om s&uacute;krom&iacute;, nav&scaron;tevujete t&uacute;to str&aacute;nku pravidelne, aby ste sa obozn&aacute;mili s&nbsp;aktu&aacute;lnou verziou. V&nbsp;pr&iacute;pade, že zmen&iacute;me ZOOU, tak&yacute;m sp&ocirc;sobom, že to bude mať na V&aacute;s dopad (tzn.&nbsp; pokiaľ m&aacute;me v&nbsp;&uacute;mysle spracov&aacute;vať Va&scaron;e osobn&eacute; &uacute;daje na in&eacute; &uacute;čely ako bolo komunikovan&eacute; v&nbsp;predch&aacute;dzaj&uacute;cej verzii ZOOU), budeme V&aacute;s informovať o&nbsp;t&yacute;chto zmen&aacute;ch e&scaron;te predt&yacute;m ako d&ocirc;jde k&nbsp;spracov&aacute;vaniu &uacute;dajov.</span></p>
<p><span style="font-weight: 400;">&bdquo;Tvrd&aacute; pravda&ldquo;: Použ&iacute;van&iacute;m tejto str&aacute;nky a/alebo využ&iacute;van&iacute;m na&scaron;ich služieb/produktov d&aacute;vate svoj s&uacute;hlas so znen&iacute;m na&scaron;ich ZOOU. Ak nes&uacute;hlas&iacute;te s&nbsp;na&scaron;imi ZOOU, mali by ste prestať využ&iacute;vať na&scaron;e služby/produkty a&nbsp;nav&scaron;tevovať t&uacute;to webov&uacute; str&aacute;nku.</span></p>
<p><span style="font-weight: 400;">Ak&eacute;koľvek inform&aacute;cie, ktor&eacute; n&aacute;m poskytnete, a&nbsp;na z&aacute;klade ktor&yacute;ch m&ocirc;žete byť identifikovan&iacute; pri použ&iacute;van&iacute; tejto webovej str&aacute;nky a&nbsp;na&scaron;ich služieb/produktov, bud&uacute; použit&eacute; v&nbsp;s&uacute;lade s&nbsp;na&scaron;imi ZOOU.&nbsp;</span></p>
<p><span style="font-weight: 400;">Tieto ZOOU stanovuj&uacute; nasleduj&uacute;ce:</span></p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ak&yacute; druh inform&aacute;ci&iacute; zhromažďujeme</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Na ak&yacute; &uacute;čel s&uacute; inform&aacute;cie použit&eacute;</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ako uchov&aacute;vame a&nbsp;chr&aacute;nime inform&aacute;cie</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ako spr&iacute;stupňujeme inform&aacute;cie</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">S&uacute;bory Cookies</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Va&scaron;e pr&aacute;va</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Kontaktn&eacute; inform&aacute;cie</span></li>
</ol>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ak&yacute; druh inform&aacute;ci&iacute; zhromažďujeme</span></li>
</ol>
<p><span style="font-weight: 400;">Inform&aacute;cie, ktor&eacute; zhromažďujeme s&uacute; nevyhnutn&eacute; na to, aby sme V&aacute;m poskytli na&scaron;e služby/produkty a/alebo sl&uacute;žia na optimaliz&aacute;ciu na&scaron;ich služieb/produktov.&nbsp; Tieto inform&aacute;cie m&ocirc;žu byť zhromažďovan&eacute; keď nav&scaron;tevujete na&scaron;u webov&uacute; str&aacute;nku, alebo keď využ&iacute;vate na&scaron;e služby (vr&aacute;tane služby &bdquo;Pr&eacute;miov&aacute; sadzba&ldquo;) a/alebo na&scaron;e produkty.</span></p>
<p><span style="font-weight: 400;">Medzi inform&aacute;cie, ktor&eacute; zhromažďujeme patria:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Meno</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Pohlavie</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">D&aacute;tum a&nbsp;čas narodenia (vek)</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Emailov&aacute; adresa</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Telef&oacute;nne č&iacute;slo</span></li>
</ul>
<p>&nbsp;</p>
<p><span style="font-weight: 400;">V&nbsp;niektor&yacute;ch pr&iacute;padoch m&ocirc;žeme zhromažďovať a&nbsp;spracov&aacute;vať nasleduj&uacute;ce inform&aacute;cie (v z&aacute;vislosti od typu služby a/alebo produktu): Va&scaron;e n&aacute;vyky (vr&aacute;tane &scaron;kodliv&yacute;ch n&aacute;vykov); kon&iacute;čky a&nbsp;rozmary; v&yacute;strelky t&yacute;kaj&uacute;ce sa jedla, oblečenia; voľno časov&eacute; aktivity atď.; obľ&uacute;ben&aacute; hudba; &scaron;port a&nbsp;&scaron;portov&eacute; v&yacute;kony; Va&scaron;e zručnosti a&nbsp;sk&uacute;senosti; osobnostn&eacute; črty a&nbsp;zručnosti; inform&aacute;cie o&nbsp;vzdelan&iacute;; rodinn&yacute; stav; miesto pobytu (mesto, krajina); pracovn&eacute; zaradenie; miesto zamestnania/&scaron;t&uacute;dia; Va&scaron;e obavy; obľ&uacute;ben&aacute; farba, krajina, mesto a&nbsp;in&eacute; preferencie; veci, ktor&eacute; m&aacute;te radi a&nbsp;nem&aacute;te radi; v&scaron;eobecn&eacute; inform&aacute;cie ohľadne du&scaron;evnej pohody (POZN&Aacute;MKA: Zhromažďujeme a&nbsp;spracov&aacute;vame iba v&scaron;eobecn&eacute; inform&aacute;cie ohľadne V&aacute;&scaron;ho zdravia, s&nbsp;vyl&uacute;čen&iacute;m diagnostick&yacute;ch d&aacute;t, d&aacute;t ohľadne chor&ocirc;b, testov, ment&aacute;lneho stavu a&nbsp;ostatn&yacute;ch anamn&eacute;z) a&nbsp;ostatn&eacute; v&scaron;eobecn&eacute; inform&aacute;cie. Okrem toho e&scaron;te automaticky zhromažďujeme inform&aacute;cie z&nbsp;V&aacute;&scaron;ho telef&oacute;nu, tabletu, mobiln&eacute;ho zariadenia alebo in&yacute;ch zariaden&iacute;, ktor&eacute; použ&iacute;vate na to, aby ste sa pripojili na na&scaron;u str&aacute;nku alebo použ&iacute;vali na&scaron;e služby a/alebo produkty. Tieto inform&aacute;cie m&ocirc;žu zahŕňať IP adresu, inform&aacute;cie, ktor&eacute; identifikuj&uacute; Va&scaron;e mobiln&eacute; zariadenie, nastavenia a&nbsp;charakteristiky &scaron;pecifick&eacute; pre jednotliv&eacute; zariadenia; inform&aacute;cie o&nbsp;tom, ak&yacute; prehliadač použ&iacute;vate; inform&aacute;cie o&nbsp;zlyhan&iacute; aplik&aacute;ci&iacute;, inform&aacute;cie o&nbsp;&uacute;čtoch na soci&aacute;lnych sieťach, ostatn&eacute; syst&eacute;mov&eacute; aktivity, inform&aacute;cie o&nbsp;jazykov&yacute;ch nastaveniach a&nbsp;nastaveniach polohy. Niekedy nast&aacute;vaj&uacute; situ&aacute;cie, kedy dost&aacute;vame inform&aacute;cie o&nbsp;V&aacute;s od in&yacute;ch subjektov, alebo automaticky zhromažďujeme ďal&scaron;ie inform&aacute;cie.</span></p>
<p><span style="font-weight: 400;">Na&scaron;a služba &bdquo;Pr&eacute;miov&aacute; sadzba&ldquo; m&ocirc;že ukladať Va&scaron;e mobiln&eacute; telef&oacute;nne č&iacute;slo; č&iacute;slo, ktor&eacute; ste vyt&aacute;čali; inform&aacute;cie o&nbsp;dĺžke a&nbsp;frekvencii Va&scaron;ich hovorov. Taktiež uklad&aacute;me inform&aacute;cie o&nbsp;ak&yacute;chkoľvek interakci&aacute;ch cez platformy soci&aacute;lnych siet&iacute; a&nbsp;f&oacute;r. Okrem toho, n&aacute;m e&scaron;te m&ocirc;žete poskytn&uacute;ť sp&auml;tn&uacute; v&auml;zbu, alebo n&aacute;s požiadať o&nbsp;pomoc použit&iacute;m na&scaron;ej služby podpory, čo taktiež zahŕňa poskytnutie osobn&yacute;ch d&aacute;t.</span></p>
<p><span style="font-weight: 400;">VYHL&Aacute;SENIE O&nbsp;ODMIENTNUT&Iacute; ZODPOVEDNOSTI: V&Scaron;ETKY INFORM&Aacute;CIE A/ALEBO &bdquo;RADY&ldquo;, &bdquo;V&Yacute;SLEDKY TESTOV&ldquo;, &bdquo;PREDPOVEDE&ldquo; OBSIAHNUT&Eacute; NA NA&Scaron;EJ WEBOVEJ STR&Aacute;NKE, V&nbsp;NA&Scaron;EJ APLIK&Aacute;CII, V&nbsp;NA&Scaron;ICH SLUŽB&Aacute;CH/PRODUKTOCH S&Uacute; POSKYTOVAN&Eacute;&nbsp; V&Yacute;HRADNE ZA &Uacute;ČELOM Z&Aacute;BAVY, A&nbsp;NEMALI BY BYŤ VYKLADAN&Eacute; AKO MEDIC&Iacute;NSKE; PR&Aacute;VNE ALEBO FINANČN&Eacute; RADY NA AK&Uacute;KOĽVEK T&Eacute;MU. SPOLOČNOSŤ ABC MOBILE O&Uuml; ODMIETA AK&Uacute;KOĽVEK ZODPOVEDNOSŤ V S&Uacute;VISLOSTI S&nbsp;ČINNOSŤAMI VYKONAN&Yacute;MI ALEBO NEVYKONAN&Yacute;MI NA Z&Aacute;KLADE NIEKTOREJ ČASTI ALEBO CEL&Eacute;HO OBSAHU NACH&Aacute;DZAJ&Uacute;CEHO SA NA TEJTO WEBOVEJ STR&Aacute;NKE. PROS&Iacute;M BERTE NA VEDOMIE, ŽE SPOLOČNOSŤ ABC MOBILE O&Uuml; NEPROPAGUJE A ANI NIE JE ZODPOVEDN&Aacute; ZA OBSAH POSKYTNUT&Yacute; TRET&Iacute;MI STRANAMI, KU KTOR&Eacute;MU JE MOŽN&Eacute; SA DOSTAŤ PROSTREDN&Iacute;CTVOM NA&Scaron;EJ WEBOVEJ STR&Aacute;NKY.</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Na ak&yacute; &uacute;čel s&uacute; inform&aacute;cie použit&eacute;</span></li>
</ol>
<p><span style="font-weight: 400;">Inform&aacute;cie použ&iacute;vame na:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">- Zabezpečenie najlep&scaron;&iacute;ch služieb.</span></li>
</ul>
<p><span style="font-weight: 400;">Na&scaron;e služby/produkty poskytujeme z&nbsp;na&scaron;ich lok&aacute;lnych kancel&aacute;ri&iacute; v&nbsp;r&ocirc;znych jazykoch, a&nbsp;sme k&nbsp;dispoz&iacute;cii 24 hod&iacute;n, 7 dn&iacute; v&nbsp;t&yacute;ždni. T&yacute;m , že ste sa podelili o&nbsp;relevantn&eacute; detaily, d&aacute;vate zamestnancom n&aacute;&scaron;ho z&aacute;kazn&iacute;ckeho oddelenia pr&iacute;ležitosť reagovať, keď n&aacute;s potrebujete &ndash; vr&aacute;tane odpovedania na Va&scaron;e ot&aacute;zky, ktor&eacute; by ste mohli mať ohľadne služieb/produktov.</span></p>
<p><span style="font-weight: 400;">-&nbsp; &bdquo;Personalizovanie&ldquo; služieb pre V&aacute;s.</span></p>
<p><span style="font-weight: 400;">Hlavn&yacute;m cieľom v&nbsp;tomto pr&iacute;pade je optimalizovať a&nbsp;prisp&ocirc;sobiť na&scaron;e služby/produkty Va&scaron;im potreb&aacute;m, aby boli pre V&aacute;s jednoduch&scaron;ie a&nbsp;čo najpr&iacute;jemnej&scaron;ie na použitie.</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Overenie, či ste dosiahli vekov&yacute; limit nevyhnutn&yacute; na využ&iacute;vanie služieb.</span></li>
</ul>
<p><span style="font-weight: 400;">Služby/produkty poskytovan&eacute; spoločnosťou ABC Mobile O&Uuml; nie s&uacute; určen&eacute; pre deti do veku 18 rokov. Využ&iacute;vanie na&scaron;ich služieb/produktov osobami mlad&scaron;&iacute;mi ako 18 rokov je povolen&eacute; iba v&nbsp;pr&iacute;pade platn&eacute;ho s&uacute;hlasu rodiča alebo ustanoven&eacute;ho pr&aacute;vneho z&aacute;stupcu. V&nbsp;pr&iacute;pade zistenia, že sprac&uacute;vame inform&aacute;cie o&nbsp;osobe mlad&scaron;ej ako 18 rokov bez platn&eacute;ho s&uacute;hlasu rodiča alebo ustanoven&eacute;ho pr&aacute;vneho z&aacute;stupcu, si vyhradzujeme pr&aacute;vo inform&aacute;cie zmazať.</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Interakciu s&nbsp;Vami a&nbsp;informovanie V&aacute;s o&nbsp;novink&aacute;ch, d&ocirc;ležit&yacute;ch oznamoch (ponuk&aacute;ch a&nbsp;akci&aacute;ch) prostredn&iacute;ctvom emailu, po&scaron;ty, telefon&aacute;tu alebo SMS spr&aacute;vy. Keď využ&iacute;vate na&scaron;e služby/produkty, m&ocirc;žeme V&aacute;m zaslať spr&aacute;vu s&nbsp;prihlasovac&iacute;mi &uacute;dajmi (prihlasovacie meno a heslo), aby ste sa mohli pripojiť k&nbsp;na&scaron;im služb&aacute;m/produktom alebo aplik&aacute;ci&aacute;m. Okrem toho, V&aacute;m e&scaron;te m&ocirc;žeme poslať dotazn&iacute;k alebo V&aacute;s m&ocirc;žeme vyzvať, aby ste ohodnotili Va&scaron;u sk&uacute;senosť s&nbsp;na&scaron;imi službami/produktmi a&nbsp;ostatn&yacute;m obsahom. Pokiaľ si nežel&aacute;te byť kontaktovan&iacute; ohľadne na&scaron;ich pon&uacute;k, akci&iacute; alebo noviniek, m&ocirc;žete sa odhl&aacute;siť z&nbsp;odberu na&scaron;ich emailov a&nbsp;SMS spr&aacute;v.</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">Zabr&aacute;nenie podvodom (Propag&aacute;cia bezpečn&yacute;ch a&nbsp;d&ocirc;veryhodn&yacute;ch služieb)</span></li>
</ul>
<p><span style="font-weight: 400;">Za &uacute;čelom vytvorenia d&ocirc;veryhodn&eacute;ho prostredia pre V&aacute;s, m&ocirc;žeme použiť osobn&eacute; &uacute;daje na odhalenie a&nbsp;predch&aacute;dzanie podvodom,&nbsp; in&yacute;ch neleg&aacute;lnych a&nbsp;nechcen&yacute;ch aktiv&iacute;t. Podobne m&ocirc;žeme použiť osobn&eacute; &uacute;daje na pos&uacute;denie rizika a&nbsp;in&eacute; bezpečnostn&eacute; &uacute;čely vr&aacute;tane autentifik&aacute;cie už&iacute;vateľov. Z&nbsp;tak&yacute;chto d&ocirc;vodov m&ocirc;žeme niektor&eacute; služby prestať poskytovať alebo dočasne pozastaviť, pokiaľ neukonč&iacute;me vyhodnotenie rizika.</span></p>
<p><span style="font-weight: 400;">Taktiež m&ocirc;žeme použ&iacute;vať a&nbsp;spracov&aacute;vať Va&scaron;e &uacute;daje a&nbsp;obsah, s&nbsp;použit&iacute;m r&ocirc;znych technol&oacute;gi&iacute;, aby sme dosiahli nasledovn&eacute;:</span></p>
<p><span style="font-weight: 400;">Zabezpečiť, aby boli dodržan&eacute; Obchodn&eacute; podmienky a&nbsp;ZOOU;&nbsp;</span></p>
<p><span style="font-weight: 400;">Kontaktovať V&aacute;s, pokiaľ sme presvedčen&iacute;, že je to nevyhnutn&eacute;;&nbsp;</span></p>
<p><span style="font-weight: 400;">Odhaliť zneužitie a&nbsp;neleg&aacute;lne aktivity; zistiť a&nbsp;predch&aacute;dzať použitiu na nespr&aacute;vny &uacute;čel, poru&scaron;eniu, kr&aacute;deži identity,&nbsp;in&yacute;m neleg&aacute;lnym aktivit&aacute;m a&nbsp;zneuž&iacute;vaniu služieb a/alebo produktov;</span></p>
<p><span style="font-weight: 400;">Rie&scaron;iť v&yacute;padky a&nbsp;poruchy;</span></p>
<p><span style="font-weight: 400;">Zah&aacute;jiť konanie v&nbsp;pr&iacute;pade ak&yacute;chkoľvek nezrovnalost&iacute;, alebo pr&aacute;vnych krokov medzi Vami a&nbsp;Službami/produktmi, alebo medzi Vami a&nbsp;ostatn&yacute;mi už&iacute;vateľmi a&nbsp;tret&iacute;mi stranami pokiaľ to s&uacute;vis&iacute; alebo ide o služby/produkty;</span></p>
<p><span style="font-weight: 400;">Dosiahnuť &uacute;čely uveden&eacute; v&nbsp;Obchodn&yacute;ch podmienkach a&nbsp;ZOOU;</span></p>
<p><span style="font-weight: 400;">Zlep&scaron;iť bezpečnosť a&nbsp;stabilitu na&scaron;ich služieb a&nbsp;produktov. Sem patr&iacute; odhalenie, prevencia a&nbsp;reagovanie na bezpečnostn&eacute; rizik&aacute; a&nbsp;technick&eacute; probl&eacute;my, ktor&eacute; m&ocirc;žu po&scaron;kodiť n&aacute;s, na&scaron;ich klientov a&nbsp;verejnosť;</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">Zabezpečenie s&uacute;ladu s&nbsp;požiadavkami nariaden&iacute;.</span></li>
</ul>
<p><span style="font-weight: 400;">Z&iacute;skan&eacute; osobn&eacute; &uacute;daje s&uacute; odoslan&eacute; a&nbsp;uložen&eacute; na bezpečn&yacute;ch serveroch&nbsp; umiestnen&yacute;ch v&nbsp;r&aacute;mci Eur&oacute;pskeho Ekonomick&eacute;ho Priestoru podľa ustanoven&iacute; nariadenia eur&oacute;pskeho parlamentu a rady (E&Uacute;) 2016/679, z 27. apr&iacute;la 2016 o ochrane fyzick&yacute;ch os&ocirc;b pri sprac&uacute;van&iacute; osobn&yacute;ch &uacute;dajov a o voľnom pohybe tak&yacute;chto &uacute;dajov.</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">- V&yacute;skum, anal&yacute;zu, aktualiz&aacute;ciu a&nbsp;vylep&scaron;enie služieb, ktor&eacute; poskytujeme.</span></li>
</ul>
<p><span style="font-weight: 400;">T Taktiež použ&iacute;vame osobn&eacute; &uacute;daje na analytick&eacute; &uacute;čely a&nbsp;merania, aby sme zistili ako s&uacute; na&scaron;e služby využ&iacute;van&eacute;. Toto je jedna časť n&aacute;&scaron;ho poslania &ndash; zlep&scaron;ovať na&scaron;e služby a&nbsp;stupňovať už&iacute;vateľsk&yacute; z&aacute;žitok, ale osobn&eacute; &uacute;daje m&ocirc;žu byť tiež použit&eacute; na testovacie &uacute;čely, rie&scaron;enie probl&eacute;mov, &nbsp;vylep&scaron;ovanie funkčnosti a&nbsp;kvality na&scaron;ich služieb/produktov a&nbsp;obsahu. Na tieto analytick&eacute; &uacute;čely sa snaž&iacute;me použ&iacute;vať iba pseudonymizovan&eacute; &uacute;daje.</span></p>
<p><span style="font-weight: 400;">Z&aacute;roveň m&ocirc;žeme monitorovať a&nbsp;nahr&aacute;vať hovory, ktor&eacute; vykon&aacute;te alebo prijmete, keď využ&iacute;vate na&scaron;e služby, za &uacute;čelom kontroly kvality (monitorovanie hovorov). A&nbsp;v&nbsp;pr&iacute;pade, že n&aacute;s kontaktujete, m&ocirc;žeme uchovať z&aacute;znam Va&scaron;ej požiadavky, aby sme mohli vyrie&scaron;iť ak&eacute;koľvek probl&eacute;my, s&nbsp;ktor&yacute;mi by ste sa mohli stretn&uacute;ť.</span></p>
<p><span style="font-weight: 400;">Vždy V&aacute;s požiadame o&nbsp;s&uacute;hlas predt&yacute;m ako použijeme inform&aacute;cie na &uacute;čel, ktor&yacute; nie je uveden&yacute; v&nbsp;t&yacute;chto ZOOU.</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ako uchov&aacute;vame a&nbsp;chr&aacute;nime inform&aacute;cie</span></li>
</ol>
<p><span style="font-weight: 400;">Dodržiavame primeran&eacute; postupy, aby sme zabr&aacute;nili neautorizovan&eacute;mu pr&iacute;stupu k&nbsp;inform&aacute;ci&aacute;m a&nbsp;zneužitiu osobn&yacute;ch &uacute;dajov.</span></p>
<p><span style="font-weight: 400;">Použ&iacute;vame vhodn&yacute; obchodn&yacute; syst&eacute;m a&nbsp;postupy, aby sme chr&aacute;nili a&nbsp;uchov&aacute;vali osobn&eacute; &uacute;daje, ktor&eacute; n&aacute;m boli zveren&eacute;. Z&aacute;roveň použ&iacute;vame bezpečnostn&eacute; postupy, technick&eacute; a&nbsp;fyzick&eacute; obmedzenia pr&iacute;stupu a&nbsp;použitia osobn&yacute;ch &uacute;dajov na na&scaron;ich serveroch. Iba opr&aacute;vnen&yacute; person&aacute;l m&aacute; pr&iacute;stup k&nbsp;osobn&yacute;m &uacute;dajom v&nbsp;r&aacute;mci ich pracovn&yacute;ch &uacute;loh. Uchov&aacute;vame Va&scaron;e osobn&eacute; &uacute;daje po dobu, ktor&uacute; považujeme za nevyhnutn&uacute; na zabezpečenie na&scaron;ich služieb/produktov (patr&iacute; sem aj uchovanie online už&iacute;vateľsk&eacute;ho &uacute;čtu, ak bol vytvoren&yacute;); po dobu, ktor&uacute; vyžaduje platn&aacute; legislat&iacute;va; pokiaľ sa nevyrie&scaron;ia nezrovnalosti s&nbsp;ktoroukoľvek stranou; a&nbsp;inak pokiaľ je to nevyhnutn&eacute;, aby sme mohli zrealizovať n&aacute;&scaron; obchod vr&aacute;tane odhalenia a&nbsp;prevencie podvodu a&nbsp;in&yacute;ch neleg&aacute;lnych aktiv&iacute;t. V&scaron;etky osobn&eacute; &uacute;daje, ktor&eacute; uchov&aacute;vame sa riadia t&yacute;mito ZOOU. Pokiaľ m&aacute;te dotaz ohľadne doby uchovania určit&eacute;ho typu osobn&yacute;ch &uacute;dajov, ktor&eacute; o&nbsp;V&aacute;s uchov&aacute;vame, pros&iacute;m kontaktujte n&aacute;s prostredn&iacute;ctvom kontaktn&yacute;ch &uacute;dajov uveden&yacute;ch v&nbsp;dolnej časti.</span></p>
<p><span style="font-weight: 400;">Inform&aacute;cie spracov&aacute;vame za &uacute;čelmi pop&iacute;san&yacute;mi v&nbsp;t&yacute;chto ZOOU, na z&aacute;klade nasleduj&uacute;cich pr&aacute;vnych d&ocirc;vodov sprac&uacute;vania:</span></p>
<p><span style="font-weight: 400;">S&nbsp;Va&scaron;im s&uacute;hlasom.</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Ako spr&iacute;stupňujeme inform&aacute;cie</span></li>
</ol>
<p><span style="font-weight: 400;">Nami z&iacute;skan&eacute; inform&aacute;cie m&ocirc;žu byť presunut&eacute; k&nbsp;na&scaron;im pridružen&yacute;m spoločnostiam a/alebo k&nbsp;tret&iacute;m stran&aacute;m, ktor&eacute; m&ocirc;žu byť situovan&eacute; mimo Eur&oacute;pskeho Ekonomick&eacute;ho Priestoru a&nbsp;&uacute;daje m&ocirc;žu byť spracov&aacute;van&eacute; person&aacute;lom pracuj&uacute;cim mimo Eur&oacute;pskeho Ekonomick&eacute;ho Priestoru. Odovzdan&iacute;m &uacute;dajov prostredn&iacute;ctvom webovej str&aacute;nky s&uacute;hlas&iacute;te s&nbsp;tak&yacute;mto uložen&iacute;m, spracov&aacute;van&iacute;m a/alebo presunom osobn&yacute;ch &uacute;dajov. Z&nbsp;času na čas m&ocirc;žeme najať ďal&scaron;ie spoločnosti alebo individu&aacute;lnych pracovn&iacute;kov aby plnili niektor&eacute; &uacute;lohy v&nbsp;na&scaron;om mene (vr&aacute;tane ale nie len, zabezpečenia služieb, pomoci s&nbsp;marketingov&yacute;mi činnosťami, anal&yacute;zy d&aacute;t, poskytovania služieb z&aacute;kazn&iacute;kom). Pri plnen&iacute; t&yacute;chto &uacute;loh sa m&ocirc;že vyžadovať pr&iacute;stup k&nbsp;Va&scaron;im osobn&yacute;m &uacute;dajom. Tam kde to vyžaduje legislat&iacute;va, m&ocirc;žeme spr&iacute;stupniť inform&aacute;cie regulačn&yacute;m a&nbsp;kontroln&yacute;m org&aacute;nom. Spr&iacute;stupňujeme osobn&eacute; &uacute;daje policajn&yacute;m a&nbsp;s&uacute;dnym org&aacute;nom iba ak si to vyžaduje legislat&iacute;va, alebo je to nevyhnutn&eacute; k&nbsp;zabr&aacute;neniu, odhaleniu alebo st&iacute;haniu krimin&aacute;lnych aktiv&iacute;t a&nbsp;podvodov, alebo ak sme z&nbsp;in&eacute;ho d&ocirc;vodu leg&aacute;lne povinn&yacute; osobn&eacute; &uacute;daje spr&iacute;stupniť. Ďalej m&ocirc;že byť nevyhnutn&eacute; spr&iacute;stupniť osobn&eacute; &uacute;daje kompetentn&yacute;m &uacute;radom, aby sme chr&aacute;nili a&nbsp;zabezpečili na&scaron;e pr&aacute;va alebo majetok, pr&iacute;padne pr&aacute;va alebo majetok na&scaron;ich obchodn&yacute;ch partnerov.</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">S&uacute;bory Cookies</span></li>
</ol>
<p><span style="font-weight: 400;">S&uacute;bory Cookies n&aacute;m umožňuj&uacute; analyzovať d&aacute;tov&eacute; toky, za &uacute;čelom marketingov&yacute;ch aktiv&iacute;t a&nbsp;lep&scaron;ie prisp&ocirc;sobiť a&nbsp;personalizovať Va&scaron;u sk&uacute;senosť s&nbsp;na&scaron;ou str&aacute;nkou t&yacute;m, že sa uložia Va&scaron;e osobn&eacute; preferencie. M&ocirc;žeme od V&aacute;s zhromažďovať inform&aacute;cie ako s&uacute; IP adresa; identifikačn&eacute; č&iacute;slo zariadenia; typ prehliadača; čas a/alebo dĺžka Va&scaron;ej n&aacute;v&scaron;tevy na str&aacute;nke; čas a/alebo dĺžka hovoru; zoznam podstr&aacute;nok, ktor&eacute; ste v&nbsp;r&aacute;mci na&scaron;ej str&aacute;nky nav&scaron;t&iacute;vili; zobrazen&eacute; str&aacute;nky; inform&aacute;cie o&nbsp;prehliadan&iacute;; operačn&yacute; syst&eacute;m; poskytovateľ internetu; oper&aacute;tor; časov&aacute; značka; inform&aacute;cia o tom, či ste reagovali na reklamu; URL adresa; použit&eacute; funkcie a&nbsp;aktivity vykonan&eacute; v&nbsp;r&aacute;mci str&aacute;nky/aplik&aacute;cie a&nbsp;in&eacute; d&aacute;ta. Použ&iacute;vame s&uacute;bory Cookies, aby sme overili autentickosť n&aacute;v&scaron;tevn&iacute;ka str&aacute;nky, aby sme V&aacute;m poskytli personalizovan&eacute; služby, aby sme umožnili monitorovanie toku d&aacute;t. V&auml;č&scaron;ina webov&yacute;ch prehliadačov automaticky akceptuje s&uacute;bory Cookies a&nbsp;podobn&eacute; technol&oacute;gie, ale ak chcete, m&ocirc;žete to zmeniť v nastaveniach prehliadača.</span></p>
<p>&nbsp;</p>
<ol>
<li style="font-weight: 400;"><span style="font-weight: 400;">Va&scaron;e pr&aacute;va</span></li>
</ol>
<p><span style="font-weight: 400;">M&aacute;te pr&aacute;vo vedieť ak&eacute; osobn&eacute; &uacute;daje o&nbsp;V&aacute;s uchov&aacute;vame. M&aacute;te pr&aacute;vo na opravu nespr&aacute;vnych &uacute;dajov. M&aacute;te pr&aacute;vo n&aacute;m zabr&aacute;niť, aby sme použili Va&scaron;e osobn&eacute; &uacute;daje na marketingov&eacute; &uacute;čely.</span></p>
<p><span style="font-weight: 400;">Taktiež n&aacute;s m&ocirc;žete požiadať o&nbsp;k&oacute;piu osobn&yacute;ch &uacute;dajov, ktor&eacute; o&nbsp;V&aacute;s uchov&aacute;vame.</span></p>
<p><span style="font-weight: 400;">Za určit&yacute;ch okolnost&iacute; n&aacute;s m&ocirc;žete požiadať, aby sme osobn&eacute; &uacute;daje, ktor&eacute; ste n&aacute;m poskytli, odoslali tretej strane. V&nbsp;pr&iacute;padoch keď uchov&aacute;vame Va&scaron;e osobn&eacute; &uacute;daje na z&aacute;klade V&aacute;&scaron;ho s&uacute;hlasu, m&aacute;te v&nbsp;r&aacute;mci z&aacute;kona pr&aacute;vo kedykoľvek odvolať tento s&uacute;hlas. Okrem toho, v&nbsp;pr&iacute;padoch keď uchov&aacute;vame Va&scaron;e osobn&eacute; &uacute;daje na z&aacute;klade legit&iacute;mneho z&aacute;ujmu alebo verejn&eacute;ho z&aacute;ujmu, m&aacute;te v&nbsp;r&aacute;mci z&aacute;kona pr&aacute;vo kedykoľvek namietať proti použ&iacute;vaniu Va&scaron;ich osobn&yacute;ch &uacute;dajov. Za &uacute;čelom ak&yacute;chkoľvek požiadaviek v&nbsp;s&uacute;vislosti s&nbsp;t&yacute;mito ZOOU a&nbsp;taktiež za &uacute;čelom uplatnenia svojho pr&aacute;va, alebo v&nbsp;pr&iacute;pade že m&aacute;te sťažnosť, kontaktujte na&scaron;u Zodpovedn&uacute; osobu za ochranu osobn&yacute;ch &uacute;dajov na adrese </span><a href="mailto:support@abcmobile.com"><span style="font-weight: 400;">support@abcmobile.com</span></a><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">Pokiaľ chcete namietať proti spracovaniu Va&scaron;ich osobn&yacute;ch &uacute;dajov na z&aacute;klade legit&iacute;mneho z&aacute;ujmu, a&nbsp;nem&aacute;te k&nbsp;dispoz&iacute;cii žiadny mechanizmus ako to urobiť priamo, m&ocirc;žete n&aacute;s kontaktovať na support@abcmobile.com.</span><span style="font-weight: 400;"><br /></span><span style="font-weight: 400;">Kontaktn&eacute; &uacute;daje</span></p>
<p><span style="font-weight: 400;">Spoločnosť ABC Mobile O&Uuml; kontroluje spracovanie osobn&yacute;ch &uacute;dajov tak ako je uveden&eacute; v t&yacute;chto ZOOU.&nbsp; Spoločnosť </span><span style="font-weight: 400;">ABC Mobile O&Uuml; je založen&aacute; podľa z&aacute;konov Est&oacute;nskej Republiky pod registračn&yacute;m č&iacute;slom 14710834, so s&iacute;dlom Harju maakond, Tallinn, Peterburi tee 71-318, 11415, Est&oacute;nsko</span><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">Pokiaľ m&aacute;te ak&yacute;koľvek dotaz ohľadne t&yacute;chto ZOOU alebo spracov&aacute;vania Va&scaron;ich osobn&yacute;ch &uacute;dajov, alebo pokiaľ ste presvedčen&iacute;, že počas využ&iacute;vania na&scaron;ich služieb/produktov bolo naru&scaron;en&eacute; Va&scaron;e s&uacute;kromie, pros&iacute;m kontaktujte na&scaron;u Zodpovedn&uacute; osobu za ochranu osobn&yacute;ch &uacute;dajov na adrese </span><a href="mailto:support@abcmobile.com"><span style="font-weight: 400;">support@abcmobile.com</span></a><span style="font-weight: 400;"> a my sa V&aacute;m čo najsk&ocirc;r ozveme sp&auml;ť.</span></p>
<p><br /><br /><br /><br /></p>
</body>
</html>