<!doctype html>
<html lang="eu">
<head>
    <meta charset="UTF-8">
    <title>Obchodné podmienky</title>
</head>
<body>
<p><span style="font-weight: 400;">Obchodn&eacute; podmienky</span></p>
<p><span style="font-weight: 400;">Tento dokument obsahuje Obchodn&eacute; podmienky, ktor&yacute;mi sa riadi použ&iacute;vanie produktov a/alebo služieb (ďalej uv&aacute;dzan&eacute; ako Služby) pon&uacute;kan&yacute;ch spoločnosťou </span><span style="font-weight: 400;">ABC Mobile O&Uuml;, založenou podľa z&aacute;konov Est&oacute;nskej Republiky pod registračn&yacute;m č&iacute;slom 14710834, so s&iacute;dlom Harju maakond, Tallinn, Peterburi tee 71-318, 11415, Est&oacute;nsko, a&nbsp;využ&iacute;van&yacute;ch už&iacute;vateľmi webovej str&aacute;nky.</span></p>
<p><span style="font-weight: 400;">Už&iacute;van&iacute;m Služieb a/alebo in&scaron;talovan&iacute;m ak&yacute;chkoľvek produktov spoločnosti ABC Mobiles už&iacute;vateľ (ka) potvrdzuje, že m&aacute; viac ako 18 rokov a&nbsp;akceptuje, že je leg&aacute;lne viazan&yacute; t&yacute;mito Obchodn&yacute;mi podmienkami a&nbsp;na&scaron;imi Z&aacute;sadami ochrany osobn&yacute;ch &uacute;dajov.</span></p>
<p><span style="font-weight: 400;">V&nbsp;pr&iacute;pade ak&yacute;chkoľvek pripomienok alebo dotazov, pros&iacute;m po&scaron;lite email na adresu </span><a href="mailto:support@abcmobile.com"><span style="font-weight: 400;">support@abcmobile.com</span></a><span style="font-weight: 400;">.</span></p>
<p><span style="font-weight: 400;">V&scaron;eobecn&eacute; ustanovenia</span></p>
<p><span style="font-weight: 400;">Na&scaron;e Služby nereprezentuj&uacute; a nezaručuj&uacute; presnosť, relevantnosť ani kvalitu inform&aacute;ci&iacute; a&nbsp;mali by byť považovan&eacute; len za inform&aacute;cie za &uacute;čelom z&aacute;bavy. Nami poskytovan&eacute; Služby nepreberaj&uacute; žiadnu zodpovednosť a&nbsp;zriekaj&uacute; sa akejkoľvek zodpovednosti voči osob&aacute;m a&nbsp;in&yacute;m pr&aacute;vnym subjektom za ak&eacute;koľvek straty alebo &scaron;kody (vr&aacute;tane a&nbsp;nielen fyzick&yacute;ch &scaron;k&ocirc;d, ment&aacute;lnych &scaron;k&ocirc;d, &scaron;peci&aacute;lnych &scaron;k&ocirc;d, nepriamych &scaron;k&ocirc;d) sp&ocirc;soben&eacute; v&nbsp;s&uacute;vislosti s&nbsp;ak&yacute;mikoľvek inform&aacute;ciami a/alebo ak&yacute;mikoľvek n&aacute;vrhmi a&nbsp;radami, poskytnut&yacute;mi prostredn&iacute;ctvom tejto Služby, alebo vzniknut&yacute;mi d&ocirc;sledkom využ&iacute;vania tejto Služby, bez ohľadu na to či vypl&yacute;vaj&uacute; z&nbsp;nedbalosti, nepredv&iacute;danej udalosti alebo akejkoľvek inej pr&iacute;činy. Poskytnut&eacute; zdravotn&eacute; a/alebo medic&iacute;nske rady by mali byť konzultovan&eacute; s&nbsp;licencovan&yacute;m lek&aacute;rom predt&yacute;m, ako budete podľa nich postupovať.</span></p>
<p><span style="font-weight: 400;">Pr&eacute;miov&aacute; sadzba</span></p>
<p><span style="font-weight: 400;">Aby ste mohli využ&iacute;vať tieto služby, mus&iacute;te byť platiteľom &uacute;čtu za telef&oacute;n alebo mať povolenie platiteľa &uacute;čtu za telef&oacute;n k&nbsp;vykonaniu hovoru. Za hovory na č&iacute;slo na&scaron;ej služby v&nbsp;r&aacute;mci Slovenska &uacute;čtujeme 2 &euro; za min&uacute;tu, plus poplatky V&aacute;&scaron;ho oper&aacute;tora za prepojenie. Maxim&aacute;lna dĺžka hovoru je 60 min&uacute;t. Hovory s&uacute; nahr&aacute;van&eacute; a&nbsp;s&uacute; určen&eacute; v&yacute;hradne pre z&aacute;bavu 18+.</span></p>
<p><span style="font-weight: 400;">Vyhl&aacute;senie o&nbsp;odmietnut&iacute; zodpovednosti,&nbsp; Autorsk&eacute; pr&aacute;va a&nbsp;ostatn&eacute; podmienky</span></p>
<p><span style="font-weight: 400;">V&scaron;etky produkty a&nbsp;služby podliehaj&uacute; autorsk&yacute;m pr&aacute;vam a&nbsp;nemali by byť kop&iacute;rovan&eacute;, zdieľan&eacute;, upravovan&eacute;, modifikovan&eacute; alebo distribuovan&eacute; ak&yacute;mkoľvek sp&ocirc;sobom. Spoločnosť </span><span style="font-weight: 400;">ABC Mobile O&Uuml; si vyhradzuje pr&aacute;vo upraviť alebo prestať poskytovať (dočasne alebo natrvalo) z&aacute;kazn&iacute;kovi služby v&nbsp;pr&iacute;pade ak:</span></p>
<ul>
<li style="font-weight: 400;"><span style="font-weight: 400;">z&aacute;kazn&iacute;k ak&yacute;mkoľvek sp&ocirc;sobom zneuž&iacute;va poskytovan&eacute; služby</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ak sa z&aacute;kazn&iacute;k ne&uacute;ctivo spr&aacute;va k&nbsp;zamestnancom alebo &nbsp;vedeniu na&scaron;ej spoločnosti</span></li>
<li style="font-weight: 400;"><span style="font-weight: 400;">ak sa z&aacute;kazn&iacute;k dopustil podvodu</span></li>
</ul>
<p><span style="font-weight: 400;">Spoločnosť </span><span style="font-weight: 400;">ABC Mobile O&Uuml; si vyhradzuje pr&aacute;vo upraviť alebo zmeniť ak&eacute;koľvek produkty alebo služby za &uacute;čelom zv&yacute;&scaron;enia kvality poskytovan&yacute;ch Služieb. Odpor&uacute;čame pravidelne kontrolovať na&scaron;u webov&uacute; str&aacute;nku, aby ste zistili ako bola zmenen&aacute; ponuka poskytovan&yacute;ch Služieb.</span></p>
<p><span style="font-weight: 400;">T&aacute;to webov&aacute; str&aacute;nka m&ocirc;že obsahovať </span><span style="font-weight: 400;">odkazy na in&eacute; str&aacute;nky prev&aacute;dzkovan&eacute; tret&iacute;mi stranami. Spoločnosť </span><span style="font-weight: 400;">ABC Mobile O&Uuml; nie je nijako prepojen&aacute; s&nbsp;t&yacute;mito str&aacute;nkami.</span></p>
<p><span style="font-weight: 400;">Za obsah zobrazen&yacute; na uveden&yacute;ch str&aacute;nkach nenesie s</span><span style="font-weight: 400;">poločnosť </span><span style="font-weight: 400;">ABC Mobile O&Uuml; žiadnu zodpovednosť, a&nbsp;ani nijak&yacute;m sp&ocirc;sobom dan&eacute; str&aacute;nky a&nbsp;služby nimi poskytovan&eacute; nepropaguje.</span></p>
<p><span style="font-weight: 400;">T&yacute;mto s&uacute;hlas&iacute;te, že v&nbsp;plnej miere oslobodzujete od zodpovednosti za &scaron;kodu spoločnosť ABC Mobile O&Uuml;, jej vedenie, riaditeľov, zamestnancov, agentov a&nbsp;poskytovateľov služieb od ak&yacute;chkoľvek n&aacute;kladov, v&yacute;davkov, str&aacute;t, &scaron;k&ocirc;d, n&aacute;rokov, a&nbsp;sp&ocirc;soben&yacute;ch podlžnost&iacute;, ktor&eacute; by mohli vznikn&uacute;ť v&nbsp;s&uacute;vislosti s&nbsp;Va&scaron;im použ&iacute;van&iacute;m webovej str&aacute;nky spoločnosti ABC Mobile O&Uuml; alebo &uacute;časti na služb&aacute;ch poskytovan&yacute;ch spoločnosťou ABC Mobile O&Uuml;.</span></p>
<p><span style="font-weight: 400;">Mieste pr&iacute;slu&scaron;n&aacute; legislat&iacute;va.&nbsp;</span></p>
<p><span style="font-weight: 400;">Tieto obchodn&eacute; podmienky sa riadia Est&oacute;nskou legislat&iacute;vou. Vy a spoločnosť ABC Mobile O&Uuml; vyhlasujete, že sa podrob&iacute;te v&yacute;lučne pr&aacute;vomoci Est&oacute;nskeho s&uacute;dneho syst&eacute;mu.</span></p>
</body>
</html>